import Image from "next/image";
import Link from "next/link";

const CATEGORIES = [
  {
    title: "Getting started",
    faqs: [
      {
        q: "What is PuzzleFlow?",
        a: "PuzzleFlow is a web-based tool for KDP (Kindle Direct Publishing) publishers. It generates unique, print-ready Sudoku puzzle books as KDP-compliant PDFs - complete with custom front matter, multiple layouts, difficulty levels, and a no-duplicate guarantee.",
      },
      {
        q: "Do I need any design or technical skills?",
        a: "None at all. You fill out a form, customize your front matter with a live preview, and download a finished PDF. The entire process takes under five minutes.",
      },
      {
        q: "How do I get started?",
        a: 'Create a free account, click "Create New Book", configure your book settings, and download your PDF. You\'ll be prompted to choose a plan before generation begins.',
      },
    ],
  },
  {
    title: "PDF & KDP compatibility",
    faqs: [
      {
        q: "Is the PDF really KDP-ready?",
        a: "Yes. Every PDF is generated to KDP's interior file specification: correct trim sizes (6×9, 8×10, or 8.5×11 inches), proper bleed (0.125″ on all sides), and KDP-compliant margins. Upload it as the interior file in KDP's book creation flow without any modifications.",
      },
      {
        q: "Which trim sizes do you support?",
        a: "We support the three most popular KDP puzzle book sizes: 6″×9″ (most popular KDP size), 8″×10″ (large print friendly), and 8.5″×11″ (recommended for puzzle books - most readable grid size).",
      },
      {
        q: "What file format is the download?",
        a: "A standard PDF file (.pdf), ready to upload directly to KDP as your interior file. No conversion or editing needed.",
      },
      {
        q: "Do I need to add a cover?",
        a: "PuzzleFlow generates the interior file only. You'll need to create or purchase a cover separately. KDP provides a free Cover Creator tool, or you can use Canva, BookBolt, or hire a designer.",
      },
      {
        q: "Can I use the PDF on other platforms besides KDP?",
        a: "Yes. The PDF is a standard print-ready file and works with any print-on-demand platform that accepts PDF interiors - including IngramSpark and Lulu.",
      },
    ],
  },
  {
    title: "Puzzles & uniqueness",
    faqs: [
      {
        q: 'What does "uniqueness guarantee" mean?',
        a: "Every puzzle generated by PuzzleFlow is cryptographically hashed and checked against a registry before it's added to your book. Book-level uniqueness means no duplicate puzzles within one book. Catalog-wide (Pro plan) means no puzzle will ever repeat across any book in your account.",
      },
      {
        q: "What difficulty levels are available?",
        a: "Easy (36–45 clues), Medium (27–35 clues), Hard (22–26 clues), Expert (17–21 clues), and Progressive - which automatically mixes Easy through Expert in order. Progressive is recommended for general-audience puzzle books.",
      },
      {
        q: "How many puzzles can I put in one book?",
        a: "Between 10 and 300 puzzles per book. Most KDP puzzle books fall in the 80–150 range - enough content to justify a price point without making the book physically too thick.",
      },
      {
        q: "What layouts are available?",
        a: "1 puzzle per page (large print, best for older audiences), 2 per page (standard - best balance of readability and page count), and 4 per page (compact - maximizes puzzle count).",
      },
    ],
  },
  {
    title: "Front matter & customization",
    faqs: [
      {
        q: "What front matter pages can I add?",
        a: "Title page (with your logo, title, subtitle, and author name), copyright page, How to Play page, and an introduction page. Answer pages are included automatically at the back of the book.",
      },
      {
        q: "Can I add my own logo or branding?",
        a: "Yes. The title page editor lets you upload your own logo image. It will appear on your title page.",
      },
      {
        q: "Can I customize fonts and grid styles?",
        a: "Yes. You can choose from several fonts (Roboto, Merriweather, Lato) and two grid styles - Standard (solid black lines) and Minimal (soft grey lines). You can also toggle page numbers, difficulty star indicators, and clue cell shading.",
      },
      {
        q: "Is there a live preview?",
        a: "Yes. When editing front matter pages, the right panel shows an exact PDF rendering of the page as you type - same font, same layout, same margins as the final download.",
      },
    ],
  },
  {
    title: "Plans & billing",
    faqs: [
      {
        q: "What's the difference between the plans?",
        a: "Pay per book ($5.99) is a single purchase with no subscription - ideal for occasional publishers. Starter ($11.99/mo) gives you 10 books per month. Pro ($23.99/mo) gives you unlimited books and catalog-wide uniqueness, meaning no puzzle ever repeats across your entire catalog.",
      },
      {
        q: "Can I switch plans?",
        a: "Yes. You can upgrade or downgrade at any time from your account settings. Changes take effect at the start of your next billing cycle.",
      },
      {
        q: "Do my PDFs expire?",
        a: "No. Every PDF you generate is yours to keep. There are no download limits or expiry dates - download your files whenever you need them.",
      },
      {
        q: "Is there a free trial?",
        a: "Yes. Every new account gets one free trial book - up to 10 puzzles, generated instantly. Trial books include a small watermark on each page. No credit card required. You'll find the option when you click 'Create New Book'.",
      },
    ],
  },
];

export default function FaqPage() {
  return (
    <div className="min-h-screen bg-white text-zinc-900 antialiased">
      {/* Nav */}
      <header className="sticky top-0 z-50 border-b border-zinc-100 bg-white/90 backdrop-blur-md">
        <div className="mx-auto flex max-w-6xl items-center justify-between px-6 py-3.5">
          <Link href="/" className="flex items-center gap-2.5">
            <Image
              src="/puzzle-flow-transparent.png"
              alt="PuzzleFlow"
              width={36}
              height={36}
              className="h-9 w-auto"
            />
            <span className="text-base font-bold">
              <span className="text-zinc-900">Puzzle</span>
              <span className="text-indigo-600">Flow</span>
            </span>
          </Link>
          <nav className="hidden items-center gap-6 md:flex">
            <Link
              href="/#how-it-works"
              className="text-sm text-zinc-500 transition-colors hover:text-zinc-900"
            >
              How it works
            </Link>
            <Link
              href="/#features"
              className="text-sm text-zinc-500 transition-colors hover:text-zinc-900"
            >
              Features
            </Link>
            <Link
              href="/pricing"
              className="text-sm text-zinc-500 transition-colors hover:text-zinc-900"
            >
              Pricing
            </Link>
            <Link href="/faq" className="text-sm font-semibold text-zinc-900">
              FAQ
            </Link>
          </nav>
          <div className="flex items-center gap-3">
            <Link
              href="/login"
              className="text-sm font-medium text-zinc-600 transition-colors hover:text-zinc-900"
            >
              Sign in
            </Link>
            <Link
              href="/dashboard"
              className="inline-flex items-center gap-2 rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white shadow-sm transition-colors hover:bg-indigo-700"
            >
              Get started
              <svg
                className="h-3 w-3"
                fill="none"
                viewBox="0 0 16 16"
                stroke="currentColor"
                strokeWidth={2.5}
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  d="M3 8h10M9 4l4 4-4 4"
                />
              </svg>
            </Link>
          </div>
        </div>
      </header>

      {/* Header */}
      <section className="bg-white pb-12 pt-20 text-center">
        <div className="mx-auto max-w-2xl px-6">
          <div className="mb-4 inline-flex items-center gap-2 rounded-full border border-indigo-100 bg-indigo-50 px-3.5 py-1.5">
            <span className="h-1.5 w-1.5 rounded-full bg-indigo-500" />
            <span className="text-xs font-semibold text-indigo-700">
              Support
            </span>
          </div>
          <h1 className="mb-4 text-5xl font-extrabold tracking-tight text-zinc-900">
            Frequently asked questions
          </h1>
          <p className="text-lg text-zinc-500">
            Everything you need to know about PuzzleFlow and publishing puzzle
            books on KDP.
          </p>
        </div>
      </section>

      {/* FAQ content */}
      <section className="bg-zinc-50 py-16">
        <div className="mx-auto max-w-3xl px-6">
          <div className="space-y-12">
            {CATEGORIES.map((cat) => (
              <div key={cat.title}>
                {/* Category heading */}
                <div className="mb-5 flex items-center gap-3">
                  <h2 className="text-base font-bold text-zinc-900">
                    {cat.title}
                  </h2>
                  <div className="h-px flex-1 bg-zinc-200" />
                </div>

                {/* Questions */}
                <div className="space-y-3">
                  {cat.faqs.map((faq) => (
                    <div
                      key={faq.q}
                      className="rounded-2xl border border-zinc-200 bg-white p-6"
                    >
                      <p className="mb-2.5 text-sm font-semibold text-zinc-900">
                        {faq.q}
                      </p>
                      <p className="text-sm leading-relaxed text-zinc-500">
                        {faq.a}
                      </p>
                    </div>
                  ))}
                </div>
              </div>
            ))}
          </div>

          {/* Still have questions */}
          <div className="mt-14 rounded-2xl border border-indigo-100 bg-indigo-50 p-8 text-center">
            <p className="mb-1 text-base font-semibold text-zinc-900">
              Still have questions?
            </p>
            <p className="mb-5 text-sm text-zinc-500">
              Can&apos;t find what you&apos;re looking for? Check the pricing
              page or get started and explore the app.
            </p>
            <div className="flex flex-wrap items-center justify-center gap-3">
              <Link
                href="/pricing"
                className="rounded-xl border border-zinc-200 bg-white px-5 py-2.5 text-sm font-medium text-zinc-700 shadow-sm transition-colors hover:bg-zinc-50"
              >
                View pricing
              </Link>
              <Link
                href="/dashboard"
                className="inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-5 py-2.5 text-sm font-semibold text-white shadow-sm transition-colors hover:bg-indigo-700"
              >
                Get started
                <svg
                  className="h-3 w-3"
                  fill="none"
                  viewBox="0 0 16 16"
                  stroke="currentColor"
                  strokeWidth={2.5}
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M3 8h10M9 4l4 4-4 4"
                  />
                </svg>
              </Link>
            </div>
          </div>
        </div>
      </section>

      {/* Footer */}
      {/* TODO: make the footer look more professional */}
      <footer className="bg-zinc-950 py-12 text-zinc-500">
        <div className="mx-auto max-w-6xl px-6">
          <div className="flex flex-col items-center justify-between gap-6 sm:flex-row">
            <Link href="/" className="flex items-center gap-2.5">
              <Image
                src="/puzzle-flow-transparent.png"
                alt="PuzzleFlow"
                width={28}
                height={28}
                className="h-7 w-auto opacity-80"
              />
              <span className="text-sm font-bold text-zinc-300">
                <span>Puzzle</span>
                <span className="text-indigo-400">Flow</span>
              </span>
            </Link>
            {/* <div className="flex items-center gap-6 text-xs">
              <Link
                href="/login"
                className="transition-colors hover:text-zinc-300"
              >
                Sign in
              </Link>
              <Link
                href="/dashboard"
                className="transition-colors hover:text-zinc-300"
              >
                Dashboard
              </Link>
              <Link
                href="/pricing"
                className="transition-colors hover:text-zinc-300"
              >
                Pricing
              </Link>
              <Link
                href="/faq"
                className="transition-colors hover:text-zinc-300"
              >
                FAQ
              </Link>
            </div> */}
            <p className="text-xs">
              © {new Date().getFullYear()} PuzzleFlow. All rights reserved.
            </p>
          </div>
        </div>
      </footer>
    </div>
  );
}
